// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add': string;
  'btn': string;
  'container': string;
  'disabled': string;
  'loading': string;
  'upload': string;
}
export const cssExports: CssExports;
export default cssExports;
