// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add': string;
  'btn': string;
  'container': string;
  'disabled': string;
  'upload': string;
}
declare var cssExports: CssExports;
export = cssExports;
