// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'container': string;
  'icon': string;
  'label': string;
}
export const cssExports: CssExports;
export default cssExports;
