// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'container': string;
  'title': string;
  'wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
