// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'container': string;
  'title': string;
  'titleContainer': string;
  'updateTime': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
