// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'down-load-icon': string;
  'icon-close': string;
  'overlay': string;
  'title': string;
  'video': string;
  'video-box': string;
}
declare var cssExports: CssExports;
export = cssExports;
