// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'bottom': string;
  'container': string;
  'isTop': string;
  'item': string;
  'parentFolderTitle': string;
  'size': string;
  'title': string;
  'top': string;
  'updateTime': string;
}
export const cssExports: CssExports;
export default cssExports;
