// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'container': string;
  'hide': string;
  'show': string;
  'tabContainer': string;
  'tabName': string;
  'tabParent': string;
}
export const cssExports: CssExports;
export default cssExports;
