// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'hide': string;
  'show': string;
  'tabContainer': string;
  'tabName': string;
  'tabParent': string;
  'tabs-container': string;
}
declare var cssExports: CssExports;
export = cssExports;
