// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folderTree': string;
  'path': string;
  'pathWrapper': string;
  'selectedFile': string;
  'treeWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
