// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'empty': string;
  'header': string;
  'loading': string;
  'name': string;
  'sort': string;
}
export const cssExports: CssExports;
export default cssExports;
