// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'bgImgs': string;
  'bgImgsMask': string;
  'btn': string;
  'container': string;
  'desc': string;
  'form': string;
  'formWrapper': string;
  'handleLogin': string;
  'handleRegister': string;
  'item': string;
  'loginBtn': string;
  'loginContainer': string;
  'mask': string;
  'registerBtn': string;
  'subCount': string;
  'subCountWrap': string;
  'submit': string;
  'wrapperMask': string;
}
export const cssExports: CssExports;
export default cssExports;
