// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'anticon': string;
  'icon-close': string;
}
declare var cssExports: CssExports;
export = cssExports;
