// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'anticon': string;
  'iconClose': string;
}
export const cssExports: CssExports;
export default cssExports;
