// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'rightContainer': string;
  'upload': string;
}
declare var cssExports: CssExports;
export = cssExports;
