// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ace_print-margin': string;
  'ant-scrolling-effect': string;
}
export const cssExports: CssExports;
export default cssExports;
