// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'right-container': string;
  'search': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
