// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btns': string;
  'comment': string;
  'commentCreateTime': string;
  'commentItem': string;
  'commentLabel': string;
  'commentList': string;
  'commentWrap': string;
  'commentorName': string;
  'comments': string;
  'container': string;
  'content': string;
  'createTime': string;
  'creator': string;
  'header': string;
  'like': string;
  'name': string;
  'noShare': string;
  'read': string;
  'right': string;
  'textarea': string;
  'title': string;
  'toolbar': string;
  'top': string;
  'userInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
