// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'container': string;
  'input-container': string;
}
declare var cssExports: CssExports;
export = cssExports;
