// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'loading': string;
  'mask': string;
  'play-angel': string;
  'play-icon': string;
}
export const cssExports: CssExports;
export default cssExports;
