// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btns': string;
  'container': string;
  'content': string;
  'header': string;
  'loading': string;
  'wange-editor': string;
}
declare var cssExports: CssExports;
export = cssExports;
