// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'emptyImg': string;
  'layout': string;
  'sider': string;
}
export const cssExports: CssExports;
export default cssExports;
