// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'layout': string;
  'sider': string;
}
declare var cssExports: CssExports;
export = cssExports;
