// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'bottom': string;
  'container': string;
  'is-top': string;
  'item': string;
  'parentFolderTitle': string;
  'size': string;
  'title': string;
  'top': string;
  'updateTime': string;
}
declare var cssExports: CssExports;
export = cssExports;
