// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btns': string;
  'container': string;
  'content': string;
  'divider': string;
  'header': string;
  'info': string;
  'loading': string;
  'markdown': string;
  'mdEditAndRead': string;
  'textareaContainer': string;
  'tips': string;
  'title': string;
  'wangeEditor': string;
}
export const cssExports: CssExports;
export default cssExports;
