// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btns': string;
  'container': string;
  'content': string;
  'divider': string;
  'header': string;
  'info': string;
  'loading': string;
  'markdown': string;
  'md-edit-and-read': string;
  'textarea-container': string;
  'tips': string;
  'title': string;
  'wange-editor': string;
}
declare var cssExports: CssExports;
export = cssExports;
